services:

  libridge-backend:
    image: rulojuka/libridge-backend:latest
    container_name: libridge-backend
    build:
      context: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/libridge
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring_profiles_active=${spring_profiles_active}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - KEYSTORE_LOCATION=/run/secrets/keystore-file
      - KEYSTORE_ALIAS=${KEYSTORE_ALIAS}
    secrets:
      - keystore-file
    ports:
      - "8080:8080"
    restart: always
    networks:
      - network-with-ben

  db:
    image: 'postgres:16.3'
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=libridge
    restart: always
    networks:
      - network-with-ben

secrets:
  keystore-file:
    file: ${KEYSTORE_LOCATION}

networks:
  network-with-ben:
    name: my-network-with-ben